definitions:
  requestparams.CollectionParams:
    properties:
      actionType:
        description: 1 点赞，-1 取消
        type: integer
      videoId:
        description: UserID     string `json:userId`
        type: integer
    type: object
  requestparams.CommentAddParams:
    properties:
      commentText:
        type: string
      videoId:
        type: integer
    type: object
  requestparams.CommentDelParams:
    properties:
      commentId:
        type: integer
    type: object
  requestparams.FavoriteParams:
    properties:
      actionType:
        description: 1 点赞，-1 取消
        type: integer
      videoId:
        description: UserID     string `json:userId`
        type: integer
    type: object
  requestparams.QiNiuTokenParams:
    properties:
      ticket:
        type: string
    required:
    - ticket
    type: object
  requestparams.StyleParams:
    properties:
      style:
        type: string
    type: object
  requestparams.UserInfoParams:
    properties:
      avatar:
        type: string
      name:
        type: string
      signature:
        type: string
      style:
        type: integer
    type: object
  requestparams.UserParams:
    properties:
      name:
        type: string
      password:
        type: string
      signature:
        type: string
    type: object
  requestparams.VideoHisParams:
    properties:
      user_id:
        type: string
      video_id:
        type: integer
      watch_ratio:
        type: number
    type: object
  requestparams.VideoUpdateParams:
    properties:
      category:
        type: integer
      cover_url:
        type: string
      desc:
        type: string
      play_url:
        type: string
      tags:
        type: string
      title:
        description: 视频名
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  description: QiYin Backend API Docs.
  title: QiYin Backend
  version: v0.0.0
paths:
  /api/v1/check:
    get:
      description: Check whether the token is valid
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: CheckToken
      tags:
      - user
  /api/v1/comment/add:
    post:
      description: add comment
      parameters:
      - description: CommentAddParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requestparams.CommentAddParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: CommentAdd
      tags:
      - comment
  /api/v1/comment/delete:
    post:
      description: Test API
      parameters:
      - description: CommentDelParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requestparams.CommentDelParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: delete comment
      tags:
      - comment
  /api/v1/comment/list:
    get:
      description: get comment list by videoId
      parameters:
      - description: query video id
        in: query
        name: videoId
        required: true
        type: string
      - description: videoId
        in: query
        name: videoId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: CommentList
      tags:
      - comment
  /api/v1/favorite/action:
    post:
      description: like or dislike
      parameters:
      - description: FavoriteParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requestparams.FavoriteParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: FavoriteAction
      tags:
      - favorite
  /api/v1/favorite/list:
    get:
      description: get favorite video list
      parameters:
      - description: query user id
        in: query
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: GetFavoriteList
      tags:
      - favorite
  /api/v1/login:
    post:
      description: user login
      parameters:
      - description: UserParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requestparams.UserParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: UserLogin
      tags:
      - user
  /api/v1/ping:
    post:
      description: Test API
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: Ping
      tags:
      - Ping
  /api/v1/qiniu/pfop/callback:
    get:
      description: Get QiNiu Pfop callback result
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: GetPfopCallback
      tags:
      - QiNiu
  /api/v1/qiniu/proxy:
    get:
      description: Get QiNiu image by proxy
      parameters:
      - description: url
        in: query
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: GetImageByProxy
      tags:
      - QiNiu
  /api/v1/qiniu/token:
    post:
      description: Get QiNiu upload token
      parameters:
      - description: QiNiuTokenParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requestparams.QiNiuTokenParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: UserLogin
      tags:
      - QiNiu
  /api/v1/register:
    post:
      description: user register
      parameters:
      - description: UserParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requestparams.UserParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: UserRegister
      tags:
      - user
  /api/v1/searchUser:
    get:
      description: search user by name
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: SearchUser
      tags:
      - user
  /api/v1/setStyle:
    post:
      description: set user style
      parameters:
      - description: StyleParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requestparams.StyleParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: SetStyle
      tags:
      - user
  /api/v1/setUser:
    post:
      description: update user info
      parameters:
      - description: UserInfoParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requestparams.UserInfoParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: SetUser
      tags:
      - user
  /api/v1/userinfo:
    get:
      description: get userinfo by id
      parameters:
      - description: query user id
        in: query
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: UserInfo
      tags:
      - user
  /api/v1/video/getHistory:
    get:
      description: get history list
      parameters:
      - description: VideoUpdateParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requestparams.VideoUpdateParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: GetHistory
      tags:
      - video
  /api/v1/video/hots:
    get:
      description: hot list
      parameters:
      - description: searchValue
        in: query
        name: searchValue
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: GetHots
      tags:
      - video
  /api/v1/video/list:
    get:
      description: get videos by userId
      parameters:
      - description: searchValue
        in: query
        name: searchValue
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: GetVideos
      tags:
      - video
  /api/v1/video/lists:
    get:
      description: get videos by userId
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: GetVideosList
      tags:
      - video
  /api/v1/video/save:
    post:
      description: video history
      parameters:
      - description: VideoHisParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requestparams.VideoHisParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: SaveVideoHis
      tags:
      - video
  /api/v1/video/search:
    get:
      description: search videos by text
      parameters:
      - description: searchValue
        in: query
        name: searchValue
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: Search
      tags:
      - video
  /api/v1/video/searchTag:
    get:
      description: search videos by tag
      parameters:
      - description: searchValue
        in: query
        name: searchValue
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: SearchTag
      tags:
      - video
  /api/v1/video/upload:
    post:
      description: hot list
      parameters:
      - description: VideoUpdateParams
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requestparams.VideoUpdateParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: UploadVideo
      tags:
      - video
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization.
    type: apiKey
swagger: "2.0"
